aurora-digital/auroradigital.co

src/components/Button/index.css
src/sections/HomePartners/index.css
src/styles/layout.css

We mustn't use/create new spacings, if they don't exist here:

Remove unnecessary spacings

---

src/pages/index.js
src/sections/HomePride/index.css
src/sections/HomePride/index.js
src/styles/all.css

Also introduces new `all.css` which allows us to import every single utility with one line.

Add "pride in creating" section to the home page

---

src/components/Navbar/index.js

Cause of the bug was the lack of a componentWillUnmount handler on the Navbar component

Fix missing scroll bug

---

package.json
src/components/BackgroundVideoText/index.css
src/sections/HomePartners/index.css
src/sections/HomePartners/index.js
yarn.lock

Using ReactCSSTransitionGroup to introduce enter/leave animations

Setup transition animation for partner cards

---

src/components/TeamElement/index.css

Should remove grayscale filter on hover

Fix team element hover effect

---

src/components/Navbar/index.js
yarn.lock

Should be overflow `visible` and not `auto`

Fix overflow property on Navbar component

---

src/components/Footer/index.js
src/components/Link/index.css
src/components/Link/index.js
src/components/Navbar/index.css
src/components/Navbar/index.js
src/components/Typography/index.css
src/components/Typography/index.js

Based on 2017 Mirror Conf's website.

Add custom Link component with hover effect

---

src/components/Footer/index.css
src/components/Footer/index.js

- Add blank target to social links

Fix addresses font height

---

src/components/Advisors/withQuery.js
src/components/Project/index.js
src/pages/index.js
src/sections/CompanyMagical/withQuery.js
src/sections/CompanyTeamSection/withQuery.js
src/sections/HomeHero/withQuery.js
src/sections/ServicesWork/withQuery.js
src/sections/TechRevolutionSection/withQuery.js

Specify sizes always and always use webp

Fix image sizes and formats

---

src/components/Navbar/index.css

Z-index should be higher than the background children

Fix z-index of navbar items

---

src/components/ListItem/index.css
src/components/ListItem/index.js
src/pages/services.js
src/sections/ServicesWork/index.css
src/sections/ServicesWork/index.js

* Also create ListItem component, to have a line with an indicator icon

Add services "work" section

---

src/components/Layout/index.css
src/components/Layout/index.js
src/components/Navbar/index.js

Remove inline style completely using Javascript, instead of setting to visible

Fix Edge overflow issue

---

src/sections/CompanyHero/index.js
src/sections/ServicesHero/index.js

There is no need to use noscript tag, because the `renderDefault` tag already takes care of that.

Remove uneeded noscript

---

src/components/Service/index.css
src/components/Service/index.js

Hide canvas in mobile and show original SVG

Fix jelly bubbles on mobile

---

src/components/Footer/socialLinks.js
src/components/Service/index.js
src/sections/HomeServices/index.css
src/sections/HomeServices/index.js
src/sections/ServicesDesign/index.js
src/sections/ServicesWork/index.js

Add view services to mobile

---

src/sections/HomeServices/index.css
src/sections/HomeServices/index.js
src/sections/ServicesWork/index.js

Also fixes go to services button to not show when device is desktop. Fix our technologies of choice to h3

Home Services center alignment 

---

package.json
src/components/Particles/index.js
src/pages/services.css
src/pages/services.js
yarn.lock

- hide particles animation on mobile
- set a different height to particles elements on tablets and desktops

Improve particles height

---

README.md
bin/functions
bin/helpers/import-nodejs-keys
bin/server
bin/setup

Pretty up the documentation before the blog post launch.

Add README.md and bin scripts

---

src/components/ParallaxEffect/index.js
src/sections/CompanyMedtechRevolution/index.js
src/sections/HomePortfolio/index.js
src/sections/HomeServices/index.js
static/robots.txt

As our CEO suggested, this fixes aim to improve SEO scores.
I added a robots.txt that allows our site to be crawled.
I also added alts to every images on the website.

Add missing alts to images and robots.txt

---

src/components/HeroCopyElement/index.css
src/components/HeroCopyElement/index.js
src/sections/HomeHero/NoScroll/index.js
src/sections/HomeHero/WithScroll/index.js
src/sections/HomeHero/common.css

Hero Section Update
Why:
- Update section for new design version
How:
- Added new copy component for the copy.
- Continuous timed roll and click change of copy message.

Hero Section Update

---

package.json
src/components/HeroCopyElement/index.css
src/components/HeroCopyElement/index.js
src/sections/HomeHero/common.css
src/styles/breakpoints.css
yarn.lock

Hero copy message animation.
Why:
- Necessary to implement bottom-up and up-bottom slide animation for hero copy message.
How:
- A timer to control which text to display and when to start a new animation.
- Used `Framer Motion` for animations.

Hero copy animation

---

src/sections/HomePortfolio/index.css
src/sections/HomeServices/index.css
src/sections/HomeServices/index.js

These changes are addressed on:
- [Fix Services and Porfolio spacings](https://3.basecamp.com/4319812/buckets/15149959/todos/2775241625)
- [Fix mobile spacing](https://3.basecamp.com/4319812/buckets/15149959/todos/2803124095)

Fix spacings
